# Generated by Django 6.0.5 on 2026-06-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='hours_learned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
