# Generated by Django 6.0.5 on 2026-06-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coursemodule_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_code_per_programme',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_slug_per_faculty',
        ),
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_student_lesson',
        ),
        migrations.RemoveConstraint(
            model_name='programme',
            name='unique_programme_per_department',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.semester'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('programme', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('department', 'name')},
        ),
    ]
