# Generated by Django 6.0.5 on 2026-06-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_semester_options_alter_studentprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='hours_learned',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='watch_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='matric_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='programme',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='programme',
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programme')),
            ],
            options={
                'unique_together': {('programme', 'course')},
            },
        ),
    ]
