# Generated by Django 6.0.5 on 2026-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='hours_learned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'name')},
        ),
    ]
