# Generated by Django 6.0.5 on 2026-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enrollment_hours_learned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Optional lesson notes or description', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4, MOV, or AVI video file', null=True, upload_to='lessons/videos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_type',
            field=models.CharField(choices=[('url', 'Video URL (YouTube / external link)'), ('file', 'Upload Video File')], default='url', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste YouTube or any video URL here', null=True),
        ),
    ]
