# Generated by Django 6.0.5 on 2026-06-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lesson_description_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('summary', 'Summary / Notes'), ('qa', 'Questions & Answers')], default='qa', max_length=10)),
                ('title', models.CharField(help_text='e.g. Week 3 Q&A or Midterm Summary', max_length=255)),
                ('content', models.TextField(help_text='Paste your questions/answers or summary text here')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_items', to='core.course')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
