# Generated by Django 6.0.5 on 2026-06-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enrollment_notified_milestones_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='last_position',
            field=models.FloatField(default=0, help_text='Video resume position in seconds'),
        ),
    ]
